### ISSUE TITLE
Got "TypeError: MultiCall is not a constructor" when using it

### ISSUE THREAD

**Issue by zhiqiangxu** [indexed-finance/multicall#5]
Minimal code to reproduce:

`script/min.js`:
```javascript
const MultiCall = require('@indexed-finance/multicall');

async function main() {
    new MultiCall(ethers.provider);
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
```

Then run `npx hardhat run script/min.js`, will report:

```
TypeError: MultiCall is not a constructor
    at main (/Users/xuzhiqiang/Desktop/workspace/opensource/solidity/scripts/min.js:4:5)
    at Object.<anonymous> (/Users/xuzhiqiang/Desktop/workspace/opensource/solidity/scripts/min.js:7:1)
```

**Comment by zhiqiangxu** [comment]
fixed by changing to this:

```javascript
const { MultiCall } = require('@indexed-finance/multicall');
```
